### ISSUE TITLE
Undelete Everything

### ISSUE THREAD

**Issue by Aftershock9880** [Aftershock9880/OmniBot2_0#1]
self explanatory

**Comment by Aftershock9880** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fix Github](https://trello.com/c/7tF1AvnR/2-fix-github)

**Comment by tomkrouper** [comment]
```
git clone https://github.com/Aftershock9880/teamcode.git
cd teamcode/
git checkout -b save_me
git log
git revert 6c6e7b1ceca8c85988644b634c589f1af1d10c8f # This is the first commit from git log.
git push origin save_me
# go to github.com/Aftershock9880/teamcode
# You should see an option to do a pull request
# do the pull request, then at the bottom there will be an option to merge the branch
```

**Comment by tomkrouper** [comment]
After the pull request is merged:
```
git checkout master
git pull
```
and your master branch on your system will have what you need.

**Comment by Aftershock9880** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fix Github](https://trello.com/c/7tF1AvnR/2-fix-github)

**Comment by Aftershock9880** [comment]
Thanks for the help Tom, however it turns out that when I tried to do the first command in the android studio terminal it complained about TeamCode already existing and I (Oliver) decided to Just work on TeleOp instead (the main computer still had the program).  When I went to commit and push (just to see if it would work) it did work. Although if we ever do delete the repository again those commands will be very useful
